include/encoders.h File Reference
wrapper around encoder functions
#include `API.h`
#include `drive.h`
Macros
#define IME_NUMBER 4
The number of IMEs. This number is compared against the number detect in init_encoders.
#define ENCODER_TILE (392 / 4 * 3.14 * 12)
defines the distance the robot needs to drive in encoder ticks
#define IME_FRONT_LEFT 1
defines the front left IME in the order
#define IME_FRONT_RIGHT 2
defines the front right IME in the order
#define IME_BACK_LEFT 0
defines the back left IME in the order
#define IME_BACK_RIGHT 3
defines the back right IME in the order
Functions
bool imeInit ()
Initializes all motor encoders.
int imeGetTicks (const unsigned char address)
Gets the encoder ticks since last reset.
int imeGetVelocityA (const unsigned char address)
Gets the encoder velocity.
void imeMoveFor (int ticks, Direction dir)
moves at a given velocity for a certain number of ticks
int imeGetAverageTicks ()
Gets the average encoder ticks since the last reset.
void imeResetAll ()
Resets all the encoders.
Detailed Description
wrapper around encoder functions
Author
Michael Baraty
Date
11/2/2018
Definition in file encoders.h.
Macro Definition Documentation
ENCODER_TILE
#define ENCODER_TILE (392 / 4 * 3.14 * 12)
defines the distance the robot needs to drive in encoder ticks
Author
Michael Baraty
Date
11/10/2018
Definition at line 28 of file encoders.h.
IME_BACK_LEFT
#define IME_BACK_LEFT 0
defines the back left IME in the order
Author
Michael Baraty
Date
11/10/2018
Definition at line 49 of file encoders.h.
Referenced by imeGetAverageTicks(), imeInit(), and imeResetAll().
IME_BACK_RIGHT
#define IME_BACK_RIGHT 3
defines the back right IME in the order
Author
Michael Baraty
Date
11/10/2018
Definition at line 56 of file encoders.h.
Referenced by imeInit(), and imeResetAll().
IME_FRONT_LEFT
#define IME_FRONT_LEFT 1
defines the front left IME in the order
Author
Michael Baraty
Date
11/10/2018
Definition at line 35 of file encoders.h.
Referenced by imeGetAverageTicks(), imeInit(), and imeResetAll().
IME_FRONT_RIGHT
#define IME_FRONT_RIGHT 2
defines the front right IME in the order
Author
Michael Baraty
Date
11/10/2018
Definition at line 42 of file encoders.h.
Referenced by imeGetAverageTicks(), imeInit(), and imeResetAll().
IME_NUMBER
#define IME_NUMBER 4
The number of IMEs. This number is compared against the number detect in init_encoders.
See also
init_encoders()
Author
Michael Baraty
Date
10/25/2018
See also
IME_NUMBER
Definition at line 21 of file encoders.h.
Referenced by imeInit().
Function Documentation
imeGetAverageTicks()
int imeGetAverageTicks ()
Gets the average encoder ticks since the last reset.
Author
Michael Baraty
Date
11/8/2018
Definition at line 48 of file encoders.c.
References IME_BACK_LEFT, IME_FRONT_LEFT, IME_FRONT_RIGHT, and imeGetTicks().
                         {
  return ((imeGetTicks(IME_FRONT_LEFT) + imeGetTicks(IME_FRONT_RIGHT) +
    imeGetTicks(IME_BACK_LEFT) + imeGetTicks(IME_FRONT_RIGHT)) / 4);
}
imeGetTicks()
int imeGetTicks (const unsigned char address)
Gets the encoder ticks since last reset.
Parameters
address
Author
Michael Baraty
Date
10/25/2018
Definition at line 21 of file encoders.c.
References imeGet().
Referenced by imeGetAverageTicks().
                                             {
  int i = 0;
  imeGet(address, &i);
  return i;
}
imeGetVelocityA()
int imeGetVelocityA (const unsigned char address)
Gets the encoder velocity.
Returns
velocity
Parameters
address
Author
Michael Baraty
Date
11/8/2018
Definition at line 27 of file encoders.c.
References imeGetVelocity().
                                                 {
  int i = 0;
  imeGetVelocity(address, &i);
  return i;
}
imeInit()
bool imeInit ()
Initializes all motor encoders.
Author
Michael Baraty
Date
10/25/2018
See also
IME_NUMBER
Definition at line 3 of file encoders.c.
References IME_BACK_LEFT, IME_BACK_RIGHT, IME_FRONT_LEFT, IME_FRONT_RIGHT, IME_NUMBER, imeInitializeAll(), imeReset(), and printf().
               {
  #ifdef IME_NUMBER
    int count = imeInitializeAll();
    if(count != IME_NUMBER) {
      printf("detected only %d\n", count);
      imeReset(0);
      return false;
    }
    imeReset(IME_FRONT_LEFT);
    imeReset(IME_FRONT_RIGHT);
    imeReset(IME_BACK_LEFT);
    imeReset(IME_BACK_RIGHT);
    return true;
  #else
    return imeInitializeAll()
  #endif
}
imeMoveFor()
void imeMoveFor (int ticks, Direction dir)
moves at a given velocity for a certain number of ticks
Parameters
ticks
dir
Author
Michael Baraty
Date
11/8/2018
Definition at line 33 of file encoders.c.
                                          {
  if(dir == forward) {
    while(true) {
      if(imeGetAverageTicks() <= ticks) {
        robotDriveStraight(forward);
      }
  }
} else if(dir == reverse) {
    while(imeGetAverageTicks() >= ticks){
      robotDriveStraight(reverse);
    }
  }
}
imeResetAll()
void imeResetAll ()
Resets all the encoders.
Author
Michael Baraty
Date
11/8/2018
Definition at line 53 of file encoders.c.
References IME_BACK_LEFT, IME_BACK_RIGHT, IME_FRONT_LEFT, IME_FRONT_RIGHT, and imeReset().
                   {
  imeReset(IME_FRONT_LEFT);
  imeReset(IME_FRONT_RIGHT);
  imeReset(IME_BACK_LEFT);
  imeReset(IME_BACK_RIGHT);
}