include/auton.h File Reference
Defines different pieces and functions for the autonomous.
#include `API.h`
Enumerations
enum AutonRoutine { far = 0,
near = 1,
none = 2
 }
defines the different possible autonomous routines
Functions
void nearRoutine ()
begins the autonomous routine from the square nearest to the flag
void farRoutine ()
begins the autonomous routine from the square farthest from the flag
Detailed Description
Defines different pieces and functions for the autonomous.
Date
11/10/2018
Author
Michael Baraty
Definition in file auton.h.
Enumeration Type Documentation
AutonRoutine
enum AutonRoutine
defines the different possible autonomous routines
Date
11/10/2018
Author
Michael Baraty
Definition at line 18 of file auton.h.
             {
  far = 0,
  near = 1,
  none = 2
} AutonRoutine;
Function Documentation
farRoutine()
void farRoutine ()
begins the autonomous routine from the square farthest from the flag
Date
11/10/2018
Author
Michael Baraty
Definition at line 70 of file auto.c.
References flywheelSet(), intakeSet(), and taskDelay().
                  {
  flywheelSet(120);
  taskDelay(4000);
  intakeSet(forward);
  taskDelay(1800);
  motorStopAll();
  }
nearRoutine()
void nearRoutine ()
begins the autonomous routine from the square nearest to the flag
Date
11/10/2018
Author
Michael Baraty
Definition at line 44 of file auto.c.
References flywheelSet(), intakeSet(), and taskDelay().
                   {
  //fire up the flywheels
  flywheelSet(70);
  taskDelay(4000);
  intakeSet(forward);
  taskDelay(1800);
  motorStopAll();
  //drive for bottom flag
  motorSet(MOTOR_BACK_LEFT, MAX_SPEED / 2);
  motorSet(MOTOR_BACK_RIGHT, MIN_SPEED / 2);
  motorSet(MOTOR_FRONT_RIGHT, MIN_SPEED / 2 + 30);
  motorSet(MOTOR_FRONT_LEFT, MIN_SPEED / 2);
  taskDelay(2000);
  robotStop();
  taskDelay(500);
  //prepare for tele-op
  motorSet(MOTOR_BACK_LEFT, -MAX_SPEED / 2);
  motorSet(MOTOR_BACK_RIGHT, -MIN_SPEED / 2);
  motorSet(MOTOR_FRONT_RIGHT, -MIN_SPEED / 2);
  motorSet(MOTOR_FRONT_LEFT, -MIN_SPEED / 2);
  taskDelay(1500);
  robotStop();
}