include/drive.h File Reference
Basic drive definitions and functions.
#include <API.h>
#include `motor_ports.h`
#include `controller.h`
#include `gyro.h`
Macros
#define THRESHOLD 20
defines the minimum reading from the joysticks to avoid underpowering the motors
Enumerations
enum Direction { forward,
reverse,
clockwise,
counterclockwise
 }
defines the directions in which the drive base can be moving
enum FlipperDirection { up,
down
 }
defines the directions in which the intake mechanism can move
Functions
void motorSpeedStick (unsigned char channel, int speed)
sets the speed of the motors according to a joystick taking into account the threshold
void robotStop ()
stops the robot drivebase
void flywheelSet (int speed)
sets the speed for the flywheel
void flywheelStop ()
stops the flywheel
void intakeSet (Direction dir)
activates the intake mechanism at a certain speed
void intakeStop ()
disables the intake mechanism
void drive ()
drives the robot
void robotSpin (Direction dir, int speed)
spins the robot in a given direction at a given speed
void robotStraighten ()
straightens the robot to face the starting direction
void robotDriveForward ()
drives the robot forward at half speed
void robotDriveStraight (Direction dir)
drives the robot straight in a given direction
void robotDriveReverse ()
drives the robot backwards at half speed
void flipperMove (FlipperDirection dir)
moves the flipper in a certain direction
void flipperStop ()
stops the cap flipper
Detailed Description
Basic drive definitions and functions.
Definition in file drive.h.
Macro Definition Documentation
THRESHOLD
#define THRESHOLD 20
defines the minimum reading from the joysticks to avoid underpowering the motors
Author
Michael Baraty
Date
10/25/2018
Definition at line 42 of file drive.h.
Referenced by joystickGetAnalogA().
Enumeration Type Documentation
Direction
enum Direction
defines the directions in which the drive base can be moving
Author
Michael Baraty
Date
10/31/2018
Definition at line 20 of file drive.h.
             {
  forward,
  reverse,
  clockwise,
  counterclockwise
} Direction;
FlipperDirection
enum FlipperDirection
defines the directions in which the intake mechanism can move
Author
Michael Baraty
Date
11/10/2018
Definition at line 32 of file drive.h.
             {
  up,
  down
} FlipperDirection;
Function Documentation
drive()
void drive ()
drives the robot
Author
Michael Baraty
Date
10/26/2018
Definition at line 41 of file drive.c.
References intakeSet(), JOY_UP, JOYSTICK_LEFT_X, JOYSTICK_LEFT_Y, JOYSTICK_MAIN, JOYSTICK_RIGHT_X, joystickGetAnalogA(), joystickGetDigital(), MOTOR_BACK_LEFT, MOTOR_BACK_RIGHT, MOTOR_FRONT_LEFT, MOTOR_FRONT_RIGHT, and motorSet().
Referenced by operatorControl().
             {
  int stickLX = joystickGetAnalogA(JOYSTICK_MAIN, JOYSTICK_LEFT_X);
  int stickLY = joystickGetAnalogA(JOYSTICK_MAIN, JOYSTICK_LEFT_Y);
  int stickRX = joystickGetAnalogA(JOYSTICK_MAIN, JOYSTICK_RIGHT_X);
  motorSet(MOTOR_FRONT_RIGHT, -(stickLY - stickRX - stickLX) * .99);
  motorSet(MOTOR_BACK_RIGHT, -(stickLY - stickRX + stickLX) * .99);
  motorSet(MOTOR_FRONT_LEFT, -(stickLY + stickRX + stickLX) * .99);
  motorSet(MOTOR_BACK_LEFT, (stickLY + stickRX - stickLX) * .99);
  if(joystickGetDigital(JOYSTICK_MAIN, 6, JOY_UP)) {
    intakeSet(forward);
  } else if(joystickGetDigital(JOYSTICK_MAIN, 6, JOY_DOWN)) {
    intakeSet(reverse);
  } else {
    intakeStop();
  }
  if(joystickGetDigital(JOYSTICK_MAIN, 5, JOY_UP)) {
    firingMode = true;
  }
  if(joystickGetDigital(JOYSTICK_MAIN, 5, JOY_DOWN)) {
    firingMode = false;
  }
  if(firingMode && joystickGetDigital(JOYSTICK_MAIN, 7, JOY_LEFT)) {
    firingSpeed = true;
  } else if(firingMode && joystickGetDigital(JOYSTICK_MAIN, 7, JOY_DOWN)) {
    firingSpeed = false;
  }
  if(firingMode && firingSpeed) {
    flywheelSet(110);
  } else if(firingMode && !firingSpeed) {
    flywheelSet(60);
  } else {
    flywheelSet(motorGet(MOTOR_FLYWHEEL_A) / 3 >= 1? motorGet(MOTOR_FLYWHEEL_A) / 3: 0);
  }
/* if(joystickGetDigital(JOYSTICK_MAIN, 8, JOY_DOWN)) {
    robotStraighten();
  }*/
  if(joystickGetDigital(JOYSTICK_MAIN, 8, JOY_UP)) {
    flipperMove(up);
  } else if(joystickGetDigital(JOYSTICK_MAIN, 8, JOY_LEFT)) {
    flipperMove(down);
  } else {
    flipperStop();
  }
}
flipperMove()
void flipperMove (FlipperDirection dir)
moves the flipper in a certain direction
Parameters
dir
Author
Michael Baraty
Date
11/6/2018
Definition at line 140 of file drive.c.
                                       {
  if(dir == up) {
    motorSet(MOTOR_FLIPPER, MIN_SPEED);
  } else if(dir == down) {
    motorSet(MOTOR_FLIPPER, MAX_SPEED);
  }
}
flipperStop()
void flipperStop ()
stops the cap flipper
Author
Michael Baraty
Date
11/10/2018
Definition at line 148 of file drive.c.
References MOTOR_FLIPPER, and motorSet().
                   {
  motorSet(MOTOR_FLIPPER, 0);
}
flywheelSet()
void flywheelSet (int speed)
sets the speed for the flywheel
Parameters
speed
Author
Michael Baraty
Date
10/26/2018
Definition at line 14 of file drive.c.
References MOTOR_FLYWHEEL_A, MOTOR_FLYWHEEL_B, and motorSet().
Referenced by farRoutine(), flywheelStop(), and nearRoutine().
                            {
  motorSet(MOTOR_FLYWHEEL_A, -speed);
  motorSet(MOTOR_FLYWHEEL_B, -speed);
}
flywheelStop()
void flywheelStop ()
stops the flywheel
Author
Michael Baraty
Date
10/26/2018
Definition at line 19 of file drive.c.
References flywheelSet().
                    {
  flywheelSet(0);
}
intakeSet()
void intakeSet (Direction dir)
activates the intake mechanism at a certain speed
Author
Michael Baraty
Date
10/31/2018
Definition at line 23 of file drive.c.
Referenced by drive(), farRoutine(), and nearRoutine().
                              {
  if(dir == forward) {
    motorSet(MOTOR_INTAKE, MIN_SPEED);
    motorSet(MOTOR_BELT, MAX_SPEED);
  } else if (dir == reverse) {
    motorSet(MOTOR_INTAKE, MAX_SPEED);
    motorSet(MOTOR_BELT, MIN_SPEED);
  } else {
    motorSet(MOTOR_INTAKE, 0);
    motorSet(MOTOR_BELT, 0);
  }
}
intakeStop()
void intakeStop ()
disables the intake mechanism
Author
Michael Baraty
Date
10/26/2018
Definition at line 36 of file drive.c.
References MOTOR_BELT, MOTOR_INTAKE, and motorSet().
                  {
  motorSet(MOTOR_INTAKE, 0);
  motorSet(MOTOR_BELT, 0);
}
motorSpeedStick()
void motorSpeedStick (unsigned char channel, int speed)
sets the speed of the motors according to a joystick taking into account the threshold
Parameters
channel
speed
Author
Michael Baraty
Date
10/25/2018
robotDriveForward()
void robotDriveForward ()
drives the robot forward at half speed
Author
Michael Baraty
Date
11/6/2018
Definition at line 116 of file drive.c.
References MAX_SPEED, MIN_SPEED, MOTOR_BACK_LEFT, MOTOR_BACK_RIGHT, MOTOR_FRONT_LEFT, MOTOR_FRONT_RIGHT, and motorSet().
                         {
  motorSet(MOTOR_BACK_LEFT, MAX_SPEED / 2);
  motorSet(MOTOR_BACK_RIGHT, MIN_SPEED / 2);
  motorSet(MOTOR_FRONT_RIGHT, MIN_SPEED / 2);
  motorSet(MOTOR_FRONT_LEFT, MIN_SPEED / 2);
}
robotDriveReverse()
void robotDriveReverse ()
drives the robot backwards at half speed
Author
Michael Baraty
Date
11/6/2018
Definition at line 123 of file drive.c.
References MAX_SPEED, MIN_SPEED, MOTOR_BACK_LEFT, MOTOR_BACK_RIGHT, MOTOR_FRONT_LEFT, MOTOR_FRONT_RIGHT, and motorSet().
                         {
  motorSet(MOTOR_BACK_LEFT, MIN_SPEED / 2);
  motorSet(MOTOR_BACK_RIGHT, MAX_SPEED / 2);
  motorSet(MOTOR_FRONT_RIGHT, MAX_SPEED / 2);
  motorSet(MOTOR_FRONT_LEFT, MAX_SPEED / 2);
}
robotDriveStraight()
void robotDriveStraight (Direction dir)
drives the robot straight in a given direction
Parameters
dir
Author
Michael Baraty
Date
11/6/2018
Definition at line 130 of file drive.c.
                                       {
  if(dir == forward) {
    robotDriveForward();
  } else if(dir == reverse) {
    robotDriveReverse();
  } else {
    robotStop();
  }
}
robotSpin()
void robotSpin (Direction dir, int speed)
spins the robot in a given direction at a given speed
Parameters
dir
speed
Author
Michael Baraty
Date
11/6/2018
Definition at line 96 of file drive.c.
Referenced by gyroTurn().
                                         {
  if(dir == clockwise) {
    motorSet(MOTOR_FRONT_RIGHT, -speed);
    motorSet(MOTOR_FRONT_LEFT, speed);
    motorSet(MOTOR_BACK_RIGHT, -speed);
    motorSet(MOTOR_FRONT_LEFT, speed);
  } else if(dir == counterclockwise) {
    motorSet(MOTOR_FRONT_RIGHT, speed);
    motorSet(MOTOR_FRONT_LEFT, -speed);
    motorSet(MOTOR_BACK_RIGHT, speed);
    motorSet(MOTOR_FRONT_LEFT, -speed);
  } else {
    robotStop();
  }
}
robotStop()
void robotStop ()
stops the robot drivebase
Author
Michael Baraty
Date
10/26/2018
Definition at line 7 of file drive.c.
References MOTOR_BACK_LEFT, MOTOR_BACK_RIGHT, MOTOR_FRONT_LEFT, MOTOR_FRONT_RIGHT, and motorSet().
                 {
  motorSet(MOTOR_BACK_LEFT, 0);
  motorSet(MOTOR_BACK_RIGHT, 0);
  motorSet(MOTOR_FRONT_RIGHT, 0);
  motorSet(MOTOR_FRONT_LEFT, 0);
}
robotStraighten()
void robotStraighten ()
straightens the robot to face the starting direction
Author
Michael Baraty
Date
11/6/2018
Definition at line 112 of file drive.c.
References gyroTurn().
                       {
  gyroTurn(0);
}