include/gyro.h File Reference
Declarations and macros for the VEX gyroscope.
#include `API.h`
#include `drive.h`
Macros
#define GYRO_PORT 1
Port the Gyroscope plugs into.
#define GYRO_MULTIPLIER 196
#define GYRO_TURN_SPEED_MAX 80
#define GYRO_TURN_SPEED_MIN_NORMAL 33
#define GYRO_TURN_SPEED_MIN_FAST 45
Functions
int gyroGetA ()
returns the main gyroscope reading
bool init_main_gyro ()
Initializes the main robot gryoscope/ Only call function when robot still and ready to start autonomous. Robot should not move for five seconds while Gyro calibrates.
void gyroTurn (int degrees)
Spins the robot to face a certain degree.
Detailed Description
Declarations and macros for the VEX gyroscope.
Author
Michael Baraty
Date
10/31/18
Definition in file gyro.h.
Macro Definition Documentation
GYRO_MULTIPLIER
#define GYRO_MULTIPLIER 196
Special Gyro multiplier for tuning in Gyro
Todo
 Todo
Definition at line 32 of file gyro.h.
Referenced by init_main_gyro().
GYRO_PORT
#define GYRO_PORT 1
Port the Gyroscope plugs into.
Author
Michael Baraty
Date
11/10/2018
Definition at line 18 of file gyro.h.
Referenced by init_main_gyro().
Function Documentation
gyroGetA()
int gyroGetA ()
returns the main gyroscope reading
Returns
gyro direction
Author
Michael Baraty
Date
11/10/2018
Definition at line 10 of file gyro.c.
References gyroGet().
Referenced by gyroTurn().
               {
  return gyroGet(main_gyro);
}
gyroTurn()
void gyroTurn (int degrees)
Spins the robot to face a certain degree.
Author
Michael Baraty
Date
10/31/18
Definition at line 14 of file gyro.c.
References gyroGetA(), and robotSpin().
Referenced by robotStraighten().
                          {
  if(gyroGetA() >= abs(degree - 180)) {
    while(gyroGetA() != degree) {
      robotSpin(counterclockwise, 70);
    }
  } else {
    while(gyroGetA() != degree) {
      robotSpin(clockwise, 70);
    }
  }
}
init_main_gyro()
bool init_main_gyro ()
Initializes the main robot gryoscope/ Only call function when robot still and ready to start autonomous. Robot should not move for five seconds while Gyro calibrates.
Returns
if the Gyro was successfully calibrated
Author
Michael Baraty
Date
10/31/18
Definition at line 5 of file gyro.c.
References GYRO_MULTIPLIER, GYRO_PORT, and gyroInit().
Referenced by initialize().
                      {
  main_gyro = gyroInit(GYRO_PORT, GYRO_MULTIPLIER);
  return main_gyro != NULL;
}